resource "local_file" "ssh_config_snippet" {
  filename        = pathexpand(var.ssh_config_snippet_path)
  file_permission = "0600"
  content = <<-EOT
    # Generated by OpenTofu — do not edit by hand.
    # Destroyed by 'tofu destroy'.
    Host sask-droplet
      HostName ${digitalocean_reserved_ip.sask.ip_address}
      User root
      IdentityFile ${pathexpand(var.ssh_private_key_path)}
      IdentitiesOnly yes
      StrictHostKeyChecking accept-new
  EOT

  depends_on = [digitalocean_reserved_ip_assignment.sask]
}
